FROM    centos:7
MAINTAINER "kkk" <kkk@jccsoftware.com>

RUN     yum install -y epel-release
# Install Node.js and npm
RUN     yum install -y nodejs npm

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
RUN npm install

# Bundle app source
COPY . /usr/src/app

EXPOSE 8800

CMD [ "npm", "start" ]
