#!/usr/bin/env node
var debug = require('debug')('exProject2_WebServer');
var app = require('./app');

app.set('port', process.env.PORT || config.web.port);

var server = app.listen(app.get('port'), function() {
    debug('Express server listening on port ' + server.address().port);
});
